### ISSUE TITLE
Package doesn't install correctly

### ISSUE THREAD

**Issue by storeyio** [okken/pytest-requests#2]
The setup.py doesn't correctly reference the pytest-requests folder.

## Expected Behavior
I should be able to install pytest-requests and run pytest without errors.

## Actual Behavior
```
(.env) [johnms pytest-requests-test]$ pytest
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.6.3, pytest-3.7.1, py-1.5.4, pluggy-0.7.1
rootdir: /home/johnms/working/pytest-requests-test, inifile:
collected 0 items                                                                                                                                                                                                 

========================================================================================== no tests ran in 0.00 seconds ===========================================================================================

(.env) [johnms pytest-requests-test]$ pip install pytest-requests
... snip ...
(.env) [johnms pytest-requests-test]$ pytest
Traceback (most recent call last):
  File "/home/johnms/working/pytest-requests-test/.env/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/home/johnms/working/pytest-requests-test/.env/lib/python3.6/site-packages/_pytest/config/__init__.py", line 55, in main
    config = _prepareconfig(args, plugins)
  File "/home/johnms/working/pytest-requests-test/.env/lib/python3.6/site-packages/_pytest/config/__init__.py", line 180, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/home/johnms/working/pytest-requests-test/.env/lib/python3.6/site-packages/pluggy/hooks.py", line 258, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/johnms/working/pytest-requests-test/.env/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/johnms/working/pytest-requests-test/.env/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/home/johnms/working/pytest-requests-test/.env/lib/python3.6/site-packages/pluggy/callers.py", line 196, in _multicall
    gen.send(outcome)
  File "/home/johnms/working/pytest-requests-test/.env/lib/python3.6/site-packages/_pytest/helpconfig.py", line 89, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/johnms/working/pytest-requests-test/.env/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/johnms/working/pytest-requests-test/.env/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/home/johnms/working/pytest-requests-test/.env/lib/python3.6/site-packages/_pytest/config/__init__.py", line 612, in pytest_cmdline_parse
    self.parse(args)
  File "/home/johnms/working/pytest-requests-test/.env/lib/python3.6/site-packages/_pytest/config/__init__.py", line 777, in parse
    self._preparse(args, addopts=addopts)
  File "/home/johnms/working/pytest-requests-test/.env/lib/python3.6/site-packages/_pytest/config/__init__.py", line 729, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/home/johnms/working/pytest-requests-test/.env/lib/python3.6/site-packages/pluggy/manager.py", line 253, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/johnms/working/pytest-requests-test/.env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/home/johnms/working/pytest-requests-test/.env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'pytest_requests'
(.env) [johnms pytest-requests-test]$ 
```
## Steps to Reproduce the Problem

Create a new venv and install pytest and pytest-requests.
1. `mkdir pytest-requests-test && cd pytest-requests-test`
2. `/usr/local/bin/python3.6 -m venv .env`
3. `source .env/bin/activate`
4. `pip install --upgrade pip pytest`
5. `pytest` runs successfully
6. `pip install pytest-requests`
7. `pytest` fails as above.

## Specifications

  - Versions:
      - Python: 3.6.3
      - pip: 18
      - pytest: 3.7.1
  - Platform: CentOS Linux release 7.4.1708 (Core)

## Investigation

After installation of pytest-requests, running a search in my venv directory doesn't yield the module itself, only the dist-info.
```
(.env) [johnms pytest-requests-test]$ find .env -name 'pytest_requests*'
.env/lib/python3.6/site-packages/pytest_requests-0.2.0.dist-info
```
Checking the `setup.py`, I can see the original cookiecutter template generated it with a `py_modules` argument to `setup`. This was originally fine as it also generated a `pytest_requests.py` single file module.

As pytest_requests is now a package and not a single file module, if I change `py_modules` to `packages`, everything works fine.

I'll submit a PR shortly.

**Comment by brumar** [comment]
The problem seems fixed, but the package uploaded at pipy is still broken to me (same error message)

**Comment by davewongillies** [comment]
I just stumbled on this issue, and it looks like the package uploaded to pypi still has this issue.

**Comment by ImnotBarbarossa** [comment]
Same problem for me with the package uploaded on pypi.

**Comment by ghop02** [comment]
Same for me!

**Comment by lczub** [comment]
Info for all, struggling with the not updated pypi - take a look to https://github.com/okken/pytest-requests/pull/3#issuecomment-411169539. It recommend to use [responses](https://github.com/getsentry/responses)

Alternative workaround
1. clone repository or download zip to e.g. _d:\git\pytest-requests_
2. `pip install d:\git\pytest-requests`
